# Generated by Django 4.1.7 on 2023-11-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('punctuation', models.PositiveSmallIntegerField(default=0, help_text='Rating from 1 to 5')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
